spring.application.name=library-system
server.port=8080

spring.datasource.url=jdbc:h2:file:./DB/librarydb;MODE=MySQL;AUTO_SERVER=TRUE;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.sql.init.schema-locations=file:./DB/ddl.sql
spring.sql.init.data-locations=file:./DB/dml.sql

spring.jpa.open-in-view=false
